version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    CLUSTER_NAME: brain-cluster
    IMAGE_REPO_NAME: brain-app

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build Docker image
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Push image
      - docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

      - echo Update kubeconfig
      - aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $CLUSTER_NAME

      - echo Deploy to EKS
      - kubectl apply -f k8s/

artifacts:
  files: []
