version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ECR_REPO: brain-tasks-app

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin 227764537166.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest 227764537166.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - docker push 227764537166.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPO:latest


